### ISSUE TITLE
PennCFA.com uses HTTP

### ISSUE THREAD

**Issue by JacobHenner** [pennlabs/common-funding-application#221]
PennCFA.com, the production version of the CFA, uses http. To ensure privacy and security, the site should only function when https is used. All old http links should redirect automatically, and HSTS should be enabled.

**Comment by adelq** [comment]
Transition to SSL started.
* All old http links now redirect to https
* cfa.pennapps.com redirects to penncfa.com

There's still some strings in the app that need to be changed and server settings configured properly.

**Comment by adelq** [comment]
Server configuration for PennCFA is pretty secure now, not perfect to remain compatible with some older browsers/operating systems.
![screenshot - 02102015 - 09 47 01 pm](https://cloud.githubusercontent.com/assets/929309/6141070/723c4fe2-b16e-11e4-8204-2835e2da1e54.png)
