### ISSUE TITLE
Escaping error in CFA-Bot email notifications.

### ISSUE THREAD

**Issue by JacobHenner** [pennlabs/common-funding-application#224]
Hello all,

When cfa-bot sends notifications for received applications, it does not properly encode (at least some) special characters (i.e. '). 

Example: `[The person&#39;s event] Event Application Received`

Thanks

**Comment by adelq** [comment]
Thanks for the bug report. It looks like we're escaping special HTML characters when we shouldn't be, I'll put in a fix whenever I get a chance. The relevant lines of code are [here](https://github.com/pennlabs/common-funding-application/blob/07f079923ebc3189ad37517fa727ba9e821e7dd3/app/models.py#L297-309), they should be passed into the `safe` filter or in an `autoescape` block.
*Note:* All email subjects must be passed through the safe filter, the email bodies should be fine.
