### ISSUE TITLE
No error page for bad URLs

### ISSUE THREAD

**Issue by adelq** [pennlabs/common-funding-application#227]
penncfa.com live deploy is currently in debug mode, which should not be the case. Errors should be logged on the server, notified to Labs team via email, and show the user a friendly but identifiable error page.

**Comment by JacobHenner** [comment]
Other PennLabs sites using Django exhibit the same issue (UA, for example).

**Comment by adelq** [comment]
Django now notifies Labs team via email, friendly error pages now in pull request.

**Comment by adelq** [comment]
Fixed for UA site (updated on here since UA site repo is private)
