### ISSUE TITLE
Productionize server for CFA

### ISSUE THREAD

**Issue by kylehg** [pennlabs/common-funding-application#90]
This involves several things, each which is probably it's own project. Consult Geoff, [Sam Panzer](mailto:panzers@seas.upenn.edu), or the current STWing sysadmin [Kai Ninomiya](mailto:kainino@stwing.upenn.edu).

- **Virtualization.** Use Xen, they're the most common. What will be tricky/interesting is migrating from our current setup (installed directly on the server) to the virutal server. It might involve some penncoursereview.com downtime, though I'm hopeful it won't be too bad. It's also possible that, on looking into this, it will be _way_ more work than it's worth, but I've been told that virtualization isn't that hard. You'll probably wan't to start by consulting Kai and go from there — feel free to CC me.
- **Set up a virtual server for each of our projects.** We currently have 4 GB of RAM to allocate and, I think, several hundred GB of HD space (though some are on separate disks that you may have to mount/unmount). We'll probably want like 1 GB for PCR (since it gets a lot of high-traffic bursts at certain times) and something more like 128–256 MB for CFA (since it will get very little).
- **Set up virtualenv on each server.** We shouldn't be installing any global Python packages. Part of this will also require going through both PCR and CFA and creating an appropriate requirements.txt file, so that deploying a project is (hopefully) only a `pip install -r requirements.txt` away.

I know it's a lot, but it will make long-term development and maintainability much more pleasant.

**Comment by adelq** [comment]
Productionized by migrating all projects to Digital Ocean in isolated VPS
