### ISSUE TITLE
Setup filesystem and MySQL backups on prod server

### ISSUE THREAD

**Issue by kylehg** [pennlabs/common-funding-application#91]
**MySQL**
MySQL is the higher priority, since most of our actual _files_ are in source control. You should do some technical due diligence on the best way to do this, but my off-the-cuff idea would be pretty simple:
- Set up a nightly cron job.
- Have the cron job mount one of our extra HDs (see `mount`/`unmount` commands and ask Kai).
- Run a mysql dump on all the DBs into the mounted HD.
- Unmount the HD

PCR data isn't changing daily but CFA data will be. In terms of how many copies to keep around, I'd say 7 daily backups, 4 weekly backups past that, and 3 monthly backups past that.

**Filesystem**
There are a number of ways to about this — one simple idea is [snapshot backups with rsync](http://www.mikerubel.org/computers/rsync_snapshots/), which could be uploaded to a remote server or a mounted/unmounted HD. Again, this is secondary to the MySQL dumps.

**Comment by adelq** [comment]
Fixed by @esqu1 and I. Nightly cron job backs up the database to S3, and database is tiny enough that we can afford daily backups for the foreseeable future.

The filesystem is backed up by Digitalocean and can be rebuilt from scratch quite easily.
